[package]
name = "rustsim"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "rustsim"
path = "src/example.rs"

[dependencies]
csv = "1.3.0"
nalgebra = "0.33.2"
wasm-bindgen = "0.2.95"
